application:
  subdomain: new-api
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://new-api:3000/

services:
  new-api:
    image: docker.1ms.run/calciumion/new-api:v0.12.12
    command: --log-dir /app/logs
    environment:
      - REDIS_CONN_STRING=redis://redis
      - ERROR_LOG_ENABLED=true
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/logs:/app/logs
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"
      start_period: 2m0s
    depends_on:
      - redis

  redis:
    image: registry.lazycat.cloud/czyt/library/redis:6108db5ea790851d
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping
      start_period: 90s