name: New API
package: lazycat.community.app.new-api
version: 0.89.31
min_os_version: 1.3.8
description: "AI模型接口管理与分发系统，支持将多种大模型转为统一格式调用，支持OpenAI、Claude等格式，可供个人或者企业内部管理与分发渠道使用，本项目基于One API二次开发"
homepage: https://github.com/QuantumNous/new-api
author: QuantumNous
application:
  subdomain: new-api
  background_task: true
  public_path:
    - /
  routes:
    - /=http://new-api:3000/
services:
  new-api:
    # docker.1ms.run/calciumion/new-api:v0.8.9.3.1
    image: registry.lazycat.cloud/czyt/calciumion/new-api:c5462d4826d43754
    ontainer_name: new-api
    command: --log-dir /app/logs
    environment:
      - REDIS_CONN_STRING=redis://redis
      - ERROR_LOG_ENABLED=true
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/logs:/app/logs
    health_check:
      test:
        - CMD-SHELL
        - "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"
      start_period: 2m0s

    depends_on:
      - redis

  redis:
    image: registry.lazycat.cloud/czyt/library/redis:6108db5ea790851d
    container_name: redis
    health_check:
      test:
        - CMD-SHELL
        - redis-cli ping
      start_period: 90s
