package: community.lazycat.app.new-api
version: 0.12.12
name: New API
description: "AI模型接口管理与分发系统，支持将多种大模型转为统一格式调用，支持OpenAI、Claude等格式，可供个人或者企业内部管理与分发渠道使用，本项目基于One API二次开发"
min_os_version: 1.5.0
homepage: https://github.com/QuantumNous/new-api
author: QuantumNous
license: MIT

locales:
  zh:
    name: "New API"
    description: "AI模型接口管理与分发系统，支持将多种大模型转为统一格式调用"
  en:
    name: "New API"
    description: "AI model interface management and distribution system"